import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import ReduxStoreProvider from "@/lib/Provider/reduxStoreProvider"
import {Bg} from "@/components/Background/Bg";
import {Nav} from "@/components/Nav/Nav";
import ThemeProviderWrapper from "@/components/themeProvider/ThemeProvider";

import React from "react";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`h-screen w-screen  overflow-y-auto overflow-x-hidden antialiased flex justify-center items-center flex-col`}>
        <AppRouterCacheProvider>

        <ReduxStoreProvider>
            <ThemeProviderWrapper>
                    <Nav/>
                <Bg variant="section">
                    {children}
                </Bg>
            </ThemeProviderWrapper>
        </ReduxStoreProvider>

        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
