import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import ReduxStoreProvider from "@/lib/Provider/reduxStoreProvider"
import {Bg} from "@/components/Background/Bg";

import ThemeProviderWrapper from "@/components/themeProvider/ThemeProvider";
import React from "react";
import {Nav} from "@/components/Nav/Nav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`h-screen w-screen ${geistSans.variable} ${geistMono.variable} overflow-hidden antialiased flex justify-center items-center flex-col`}>
        <AppRouterCacheProvider>

        <ReduxStoreProvider>
            <ThemeProviderWrapper>
                <Bg variant="section">
                    <Nav/>
                    {children}
                </Bg>
            </ThemeProviderWrapper>
        </ReduxStoreProvider>

        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
